export const topicsListHeader = [
  'topic',
  'author',
  'posts',
  'views',
  'last_reply',
];

export const dummyTopics = [
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
  {
    topic: 'topic',
    author: 'nickname',
    postCount: 1,
    viewsCount: 1,
    lastReplay: 'today',
  },
];
